# Generated by Django 4.2 on 2023-04-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_list',
            new_name='customer',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
    ]
