# Generated by Django 4.2 on 2023-04-19 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_customer_city_alter_customer_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Zıİ]+$', message='Sadece harf kullanılabilir.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Zıİ]+$', message='Sadece harf kullanılabilir.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Zıİ]+$', message='Sadece harf kullanılabilir.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Zıİ]+$', message='Sadece harf kullanılabilir.')]),
        ),
    ]
